# Generated by Django 5.2.17 on 2026-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('furniture', models.TextField()),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='fi', max_length=2)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('done', 'Done')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('price_eur', models.PositiveIntegerField()),
                ('is_hourly', models.BooleanField(default=False)),
                ('label_en', models.CharField(max_length=150)),
                ('label_fi', models.CharField(blank=True, max_length=150)),
                ('label_sv', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question_en', models.CharField(max_length=200)),
                ('question_fi', models.CharField(blank=True, max_length=200)),
                ('question_sv', models.CharField(blank=True, max_length=200)),
                ('answer_en', models.TextField()),
                ('answer_fi', models.TextField(blank=True)),
                ('answer_sv', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(help_text='Large photos are resized automatically', upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('price_eur', models.PositiveIntegerField()),
                ('estimated_hours', models.PositiveSmallIntegerField(default=1)),
                ('referral_bonus_eur', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_fi', models.CharField(blank=True, max_length=100)),
                ('name_sv', models.CharField(blank=True, max_length=100)),
                ('description_en', models.CharField(max_length=200)),
                ('description_fi', models.CharField(blank=True, max_length=200)),
                ('description_sv', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+358 40 871 3636', max_length=30)),
                ('whatsapp_number', models.CharField(default='358408713636', help_text='Digits only, with country code', max_length=20)),
                ('telegram_username', models.CharField(blank=True, help_text='Without @. Leave empty to hide Telegram buttons', max_length=50)),
                ('email', models.EmailField(default='info@sisuseth.com', max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('service_areas', models.CharField(default='Helsinki, Espoo, Vantaa', help_text='Comma separated', max_length=200)),
                ('happy_customers', models.PositiveIntegerField(default=500)),
                ('starting_price_eur', models.PositiveIntegerField(default=50)),
                ('hourly_rate_eur', models.PositiveIntegerField(default=40)),
                ('additional_item_eur', models.PositiveIntegerField(default=45, help_text='Calculator: price per extra item')),
                ('brands', models.CharField(default='IKEA, JYSK, Sotka, ISKU, Treetale, Kodin1', help_text='Comma separated', max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, help_text='Big photo at the top of the page', upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('quote_en', models.TextField()),
                ('quote_fi', models.TextField(blank=True)),
                ('quote_sv', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('note', models.CharField(blank=True, help_text='Where this text appears', max_length=200)),
                ('value_en', models.TextField()),
                ('value_fi', models.TextField(blank=True)),
                ('value_sv', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
