# Generated by Django 5.2.17 on 2026-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('before', models.ImageField(upload_to='before_after/')),
                ('after', models.ImageField(upload_to='before_after/')),
                ('caption_en', models.CharField(blank=True, max_length=150)),
                ('caption_fi', models.CharField(blank=True, max_length=150)),
                ('caption_sv', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Before/after photos',
                'verbose_name_plural': 'Before/after photos',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='e.g. PAX wardrobe 100×58×236', max_length=100)),
                ('brand', models.CharField(default='IKEA', max_length=50)),
                ('price_eur', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField(help_text='Our typical assembly time')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(help_text='Short MP4, ideally under 10 MB', upload_to='videos/')),
                ('poster', models.ImageField(blank=True, help_text='Optional still image shown while loading', upload_to='videos/')),
                ('caption_en', models.CharField(blank=True, max_length=150)),
                ('caption_fi', models.CharField(blank=True, max_length=150)),
                ('caption_sv', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_before_after',
            field=models.BooleanField(default=True, verbose_name='Before/after photo slider'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_google_reviews',
            field=models.BooleanField(default=False, verbose_name='Google reviews (needs GOOGLE_PLACES_API_KEY + place ID)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_hero_animation',
            field=models.BooleanField(default=True, verbose_name='Flat-pack box animation in the hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_hours_counter',
            field=models.BooleanField(default=True, verbose_name="'Weekend hours saved' counter"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_mobile_bar',
            field=models.BooleanField(default=True, verbose_name='Sticky booking bar on phones'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_product_search',
            field=models.BooleanField(default=True, verbose_name="Product price search (e.g. 'PAX' → price)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_quiz',
            field=models.BooleanField(default=True, verbose_name="'How long would it take you?' quiz"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_referrals',
            field=models.BooleanField(default=True, verbose_name='Referral codes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_tax_credit',
            field=models.BooleanField(default=True, verbose_name='Household tax credit (kotitalousvähennys) calculator'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_timeline_animation',
            field=models.BooleanField(default=True, verbose_name='Animated DIY vs SISUSETH timeline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_videos',
            field=models.BooleanField(default=True, verbose_name='Video strip (short clips)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_place_id',
            field=models.CharField(blank=True, help_text="From Google's Place ID Finder", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_per_job',
            field=models.DecimalField(decimal_places=1, default=3, help_text='Weekend hours saved per completed booking', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_saved_base',
            field=models.PositiveIntegerField(default=1000, help_text='Hours saved before bookings were tracked here'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quiz_average_multiplier',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quiz_beginner_multiplier',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quiz_handy_multiplier',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_discount_eur',
            field=models.PositiveIntegerField(default=10, help_text='Discount for the friend who books with a code'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_credit_deductible_eur',
            field=models.PositiveIntegerField(default=150, help_text='Yearly own-liability per person'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_credit_labour_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='Share of the price that is labour'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_credit_max_eur',
            field=models.PositiveIntegerField(default=1600, help_text='Yearly maximum per person'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_credit_rate_percent',
            field=models.PositiveSmallIntegerField(default=35),
        ),
    ]
