# Generated by Django 5.2.17 on 2026-09-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='feature_google_reviews',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='feature_referrals',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='google_place_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='referral_discount_eur',
        ),
    ]
