# Generated by Django 5.2.17 on 2026-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_reviews_referrals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji, e.g. 🔧', max_length=8)),
                ('title_en', models.CharField(max_length=100)),
                ('title_fi', models.CharField(blank=True, max_length=100)),
                ('title_sv', models.CharField(blank=True, max_length=100)),
                ('text_en', models.CharField(max_length=200)),
                ('text_fi', models.CharField(blank=True, max_length=200)),
                ('text_sv', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Frustration card',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title_en', models.CharField(max_length=100)),
                ('title_fi', models.CharField(blank=True, max_length=100)),
                ('title_sv', models.CharField(blank=True, max_length=100)),
                ('text_en', models.CharField(max_length=250)),
                ('text_fi', models.CharField(blank=True, max_length=250)),
                ('text_sv', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('side', models.CharField(choices=[('diy', 'DIY weekend'), ('us', 'SISUSETH weekend')], max_length=3)),
                ('time', models.CharField(help_text='e.g. 10:30', max_length=10)),
                ('text_en', models.CharField(max_length=200)),
                ('text_fi', models.CharField(blank=True, max_length=200)),
                ('text_sv', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Weekend timeline row',
                'verbose_name_plural': 'Weekend timeline rows',
                'ordering': ['side', 'order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seeded_sections',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
