# Generated by Django 5.2.17 on 2026-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_editable_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_mobile_bar',
            field=models.BooleanField(default=True, verbose_name='Floating contact button (WhatsApp / Telegram / Call)'),
        ),
    ]
